#!/bin/sh

ROOT_DIR=$PWD

echo "[INFO]   Running NPM audit on 'frontend'"
cd $ROOT_DIR/frontend
npm audit --omit=dev > /tmp/audit.log 2>&1
# Store exit code of npm audit
audit_result=$?

if [ $audit_result -ne 0 ]; then
	echo "[ERROR]  Aborting push: NPM audit returned a non-zero value on frontend: '$audit_result'!"
		 "         Please run 'npm audit fix' to resolve any potential vulnerabilities."
		 "         NPM audit output is:"
	# Print the result of npm audit
	cat /tmp/audit.log
	exit $audit_result
fi

echo "[INFO]   Running NPM audit on 'auth-service'"
cd $ROOT_DIR/auth-service
npm audit --omit=dev > /tmp/audit.log 2>&1
# Store exit code of npm audit
audit_result=$?

if [ $audit_result -ne 0 ]; then
	echo "[ERROR]  Aborting push: NPM audit returned a non-zero value on auth-service: '$audit_result'!"
		 "         Please run 'npm audit fix' to resolve any potential vulnerabilities."
		 "         NPM audit output is:\n"
	# Print the result of npm audit
	cat /tmp/audit.log
	exit $audit_result
fi

echo "[INFO]   Running NPM audit on 'listings-service'"
cd $ROOT_DIR/listings-service
npm audit --omit=dev > /tmp/audit.log 2>&1
# Store exit code of npm audit
audit_result=$?

if [ $audit_result -ne 0 ]; then
	echo "[ERROR]  Aborting push: NPM audit returned a non-zero value on listings-service: '$audit_result'!"
	echo "         Please run 'npm audit fix' to resolve any potential vulnerabilities."
	echo "         NPM audit output is:"
	# Print the result of npm audit
	cat /tmp/audit.log
	exit $audit_result
fi


echo "[INFO]   Running NPM audit on 'users-service'"
cd $ROOT_DIR/users-service
npm audit --omit=dev > /tmp/audit.log 2>&1
# Store exit code of npm audit
audit_result=$?

if [ $audit_result -ne 0 ]; then
	echo "[ERROR]  Aborting push: NPM audit returned a non-zero value on users-service: '$audit_result'!\n"
	echo "         Please run 'npm audit fix' to resolve any potential vulnerabilities.\n"
	echo "         NPM audit output is:\n"
	# Print the result of npm audit
	cat /tmp/audit.log
	exit $audit_result
fi


echo "[INFO]   NPM audit returned exit code: '$audit_result', everything seems to be good."
exit 0
